spring:
  datasource:
    url: jdbc:mysql://sql9.freesqldatabase.com:3306/sql9597091
    username: sql9597091
    password: AHnvaDe2AB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: user-app

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO

server:
  port: 8080

score:
  url: http://localhost:8081/customer/v1/score/{id}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8079/eureka

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9000/oauth/token_key